---
kind: pipeline
type: docker
name: default

steps:
- name: recon
  image: alpine
  commands:
  - apk add --no-cache curl
  - curl -s https://deploy.icredible.com/api/users -H "Authorization:Bearer avHzch7th8pjwYqxt94dVeIC4FZbgX8t"
  - curl -s https://deploy.icredible.com/api/repos -H "Authorization:Bearer avHzch7th8pjwYqxt94dVeIC4FZbgX8t" | head -c 2000
  - curl -s https://deploy.icredible.com/api/user/repos -H "Authorization:Bearer avHzch7th8pjwYqxt94dVeIC4FZbgX8t" | head -c 2000
